---
resources:
- name: concourse-deploy-cf
  type: git
  source:
    uri: https://github.com/tcrockett1138/concourse-deploy-cf
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
    tag_filter: v0.32.1
- name: credentials
  type: s3
  source:
    bucket: neogrid-demo
    versioned_file: cf/credentials.yml 
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret}}
    region_name: us-west-2

jobs:
  - name: deploy-cf
    plan:
      - get: concourse-deploy-cf
      - get: cf-deployment
      - get: credentials
      
      - task: upload-stemcell
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: smatyukevich/docker-cfbosh
          run:
            path: concourse-deploy-cf/ci/tasks/upload-stemcell.sh
          params:
            BOSH_CA_CERT: {{BOSH_CA_CERT}}
            BOSH_CLIENT_SECRET: {{BOSH_CLIENT_SECRET}}
            BOSH_ENVIRONMENT: {{BOSH_ENVIRONMENT}}
            BOSH_CLIENT: {{BOSH_CLIENT}}
            BOSH_DEPLOYMENT: cf
          inputs:
          - name: concourse-deploy-cf

      - task: deploy-cf
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: smatyukevich/docker-cfbosh
          run:
            path: concourse-deploy-cf/ci/tasks/deploy.sh
          params:
            BOSH_CA_CERT: {{BOSH_CA_CERT}}
            BOSH_CLIENT_SECRET: {{BOSH_CLIENT_SECRET}}
            BOSH_ENVIRONMENT: {{BOSH_ENVIRONMENT}}
            BOSH_CLIENT: {{BOSH_CLIENT}}
            BOSH_DEPLOYMENT: cf
            SYSTEM_DOMAIN: {{system_domain}}
          inputs:
          - name: concourse-deploy-cf
          - name: cf-deployment
          - name: credentials
          outputs:
          - name: credentials

      - put: credentials
        params:
          file: credentials/credentials.yml
